language: python
python:
  - "2.7"
  - "3.6"

env:
  global:
    - PYTHONPATH=.
    - ES_VERSION=6.5.4
    - ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-$ES_VERSION.tar.gz

install:
  - "wget $ES_DOWNLOAD_URL"
  - "tar -xzf elasticsearch-$ES_VERSION.tar.gz"
  - "sudo cp -f tests/travis/elasticsearch.yml ./elasticsearch-${ES_VERSION}/config/elasticsearch.yml"
  - "./elasticsearch-$ES_VERSION/bin/elasticsearch &"
  - "pip install -r requirements.txt"
  - "pip install -r tests/requirements.txt"
  - "wget -q --waitretry=1 --retry-connrefused -T 10 -O - http://127.0.0.1:9200"

# command to run tests
script:
  - "python -m unittest discover tests"

